# Generated by Django 3.2.12 on 2022-02-20 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/no-img.jpg', null=True, upload_to='avatar', verbose_name='تصوير'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 0, 30, 17, 254196, tzinfo=utc), null=True, verbose_name='تاريخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv_en',
            field=models.FileField(blank=True, default='avatar/no-img.jpg', null=True, upload_to='cv', verbose_name=' فايل رزومه براي سايت انگليسي '),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv_fa',
            field=models.FileField(blank=True, default='avatar/no-img.jpg', null=True, upload_to='cv', verbose_name=' فايل رزومه براي سايت فارسي '),
        ),
    ]
