# Generated by Django 3.2.12 on 2022-02-20 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0003_auto_20220219_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم گيت هاب'),
        ),
        migrations.AddField(
            model_name='user',
            name='googlescholar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم گوگل اسكولار'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم اينستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=' نام خانوادگي در سايت انگليسي '),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fa',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگي در سايت فارسي '),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم لينكدين'),
        ),
        migrations.AddField(
            model_name='user',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم اسكايپ'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم تلگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم توييتر'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم گيت هاب'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' كانال يوتوب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 0, 54, 18, 690017, tzinfo=utc), null=True, verbose_name='تاريخ تولد'),
        ),
    ]
