# Generated by Django 3.2.12 on 2022-02-20 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0004_auto_20220219_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 1, 8, 18, 740054, tzinfo=utc), null=True, verbose_name='تاريخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='  شماره واتس اپ'),
        ),
    ]
