# Generated by Django 3.2.12 on 2022-02-20 22:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0005_auto_20220219_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, max_length=20, null=True, verbose_name=' نام سرويس در سايت فارسي ')),
                ('title_en', models.CharField(blank=True, max_length=20, null=True, verbose_name=' عنوان سرويس در سايت انگليسي ')),
                ('describtion_fa', models.TextField(blank=True, null=True, verbose_name='توضيحات سرويس در سايت فارسي ')),
                ('describtion_en', models.TextField(blank=True, null=True, verbose_name='توضيحات سرويس در سايت انگليسي ')),
            ],
            options={
                'verbose_name': 'سرويس',
                'verbose_name_plural': 'سرويس ها',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 22, 32, 49, 635235, tzinfo=utc), null=True, verbose_name='تاريخ تولد'),
        ),
    ]
